// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4n2eOGNRzg1GnukJJHWeLS3NKVGlRGsw',
    appId: '1:314583170778:web:f7abb636872c0d772c2fe3',
    messagingSenderId: '314583170778',
    projectId: 'diet-workout-app',
    authDomain: 'diet-workout-app.firebaseapp.com',
    storageBucket: 'diet-workout-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk5Fx6-f82DVRKmONAxc6-z1Lklm33Tq8',
    appId: '1:314583170778:android:25c8611736b5d4272c2fe3',
    messagingSenderId: '314583170778',
    projectId: 'diet-workout-app',
    storageBucket: 'diet-workout-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACawD8uPWyUUlbDiPE8mt_zsGJAV8-MYI',
    appId: '1:314583170778:ios:29765d3b7832103c2c2fe3',
    messagingSenderId: '314583170778',
    projectId: 'diet-workout-app',
    storageBucket: 'diet-workout-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACawD8uPWyUUlbDiPE8mt_zsGJAV8-MYI',
    appId: '1:314583170778:ios:29765d3b7832103c2c2fe3',
    messagingSenderId: '314583170778',
    projectId: 'diet-workout-app',
    storageBucket: 'diet-workout-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4n2eOGNRzg1GnukJJHWeLS3NKVGlRGsw',
    appId: '1:314583170778:web:e3241bf746be6c2a2c2fe3',
    messagingSenderId: '314583170778',
    projectId: 'diet-workout-app',
    authDomain: 'diet-workout-app.firebaseapp.com',
    storageBucket: 'diet-workout-app.firebasestorage.app',
  );
}
